---
- name: debian | installing packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-mirror

- name: debian | ensuring apt_mirror_dir exists
  file:
    dest: "{{ apt_mirror_dir }}"
    state: directory

- name: debian | configuring apt-mirror
  template:
    src: "etc/apt/mirror.list.j2"
    dest: "/etc/apt/mirror.list"
    owner: root
    group: root
    mode: 0644
  register: apt_repos_updated

- name: debian | populating repos
  command: "apt-mirror"
  when: >
        apt_repos_updated.changed and
        (apt_mirror_populate_repos is defined and apt_mirror_populate_repos)

- name: debian | configuring apt-mirror cron (if enabled)
  cron:
    name: "{{ item.name }}"
    special_time: "{{ item.special_time|default(omit) }}"
    minute: "{{ item.minute|default(omit) }}"
    hour: "{{ item.hour|default(omit) }}"
    day: "{{ item.day|default(omit) }}"
    month: "{{ item.month|default(omit) }}"
    weekday: "{{ item.weekday|default(omit) }}"
    user: "apt-mirror"
    job: "{{ item.job }}"
    cron_file: "{{ item.cron_file }}"
  when: >
        apt_mirror_schedule_updates is defined and
        apt_mirror_schedule_updates

- name: debian | configuring Apache2 symlinks for repo(s)
  file:
    src: "{{ apt_mirror_dir }}/mirror/{{ item.uri }}"
    dest: "{{ apache2_default_root }}/{{ item.distro }}"
    owner: www-data
    group: www-data
    state: link
    force: yes  #we do this because the src may/may not exist yet
  with_items: apt_mirror_apache_links
