---
- name: debian | installing packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-mirror

- name: debian | ensuring apt_mirror_dir exists
  file:
    dest: "{{ apt_mirror_dir }}"
    state: directory

- name: debian | configuring apt-mirror
  template:
    src: "etc/apt/mirror.list.j2"
    dest: "/etc/apt/mirror.list"
    owner: root
    group: root
    mode: 0644
  register: apt_repos_updated

- name: debian | populating repos
  command: "apt-mirror"
  when: >
    apt_repos_updated.changed and \
    (apt_mirror_populate_repos is defined and apt_mirror_populate_repos)
